### ISSUE TITLE
Support for Gnome 40

### ISSUE THREAD

**Issue by echeoquehaii** [Zefty/AutoNightLight#1]
Hi @Zefty!
Thanks for this great extension, is just what I needed since I use NightLight through the whole day, but just in different intensities depending on the time of the day.
I've installed it today on Manjaro with Gnome 40, but the extension doesn't seem to work. Could you help me fix it?

This what I get when opening the extension's settings:

> 
> The settings of extension autonightlight@zefty.github.io had an error:
> ```
> Gtk.BuilderError: /home/***/.local/share/gnome-shell/extensions/autonightlight@zefty.github.io/prefs.ui:44:36 Invalid property: GtkLabel.ypad
> ```
> 
> Stack trace:
> ```
> _init@/home/***/.local/share/gnome-shell/extensions/autonightlight@zefty.github.io/prefs.js:43:23
> wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
> buildPrefsWidget@/home/***/.local/share/gnome-shell/extensions/autonightlight@zefty.github.io/prefs.js:222:17
> _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
> OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> run@resource:///org/gnome/gjs/modules/script/package.js:206:19
> start@resource:///org/gnome/gjs/modules/script/package.js:190:8
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```

**Comment by Zefty** [comment]
Hi @carallo thanks for reminding about gnome 40 support. Have been busy with exams! Will try and update the extension by the end of the week. Cheers!

**Comment by Zefty** [comment]
@carallo Hey I have fixed the above issues by adding gnome40 support. Just waiting for the gnome extension guys to approve the update on the website. Cheers!

**Comment by echeoquehaii** [comment]
Hey @Zefty, that was blazing fast, I couldn't even reply in time. 
Thank you so much, will try it as soon as it gets pushed to the extensions website.

EDIT: Works perfectly, thank you!!
